### ISSUE TITLE
Possibility to know when a component is used

### ISSUE THREAD

**Issue by smendez-hi** [SIMPATICOProject/IFE#2]
From our side is more useful to know if a component has been used instead of if it's enabled or not. I will use the function `isEnabled` but i wanted to know if it could be added or not.
Thanks in advance.

**Comment by xPret** [comment]
According to the "Development of a new feature" section, you can add several public or private methods inside your implementation (see [STEP4] and [STEP5]). If you are talking about the log client, the way to know whether a component is used is by registering the log calls internally.
Regards

**Comment by smendez-hi** [comment]
I'm talking about the Citizenpedia and Simplification, sorry. I don't want to touch your code, that's why I was asking. Because is not the most accurate thing to assume that an user used one of the components because they clicked on the top bar (that is when `featureEnabled` is true)

**Comment by smendez-hi** [comment]
Now using the information stored in the database, so no need for this.
